### PR TITLE
Fix acequire undefined error

### PR DESCRIPTION
**Pull request by ajinkyasurya**
TypeError: Cannot read property 'acequire' of undefined

### CODE REVIEW

**Comment by JackuB** [comment]
Hi, first, thanks a lot for the PR! 🎉 

Is this related to #49?
`acequire` is needed for compatibility with [brace](https://github.com/thlorenz/brace).

Could you tell me a bit for about your setup? I saw you did a few edits there. Are you using webpack? Babel? Global Ace editor or brace?

**Comment by ajinkyasuryawanshi-okta** [comment]
Hi @JackuB thanks for getting back to me. Yes it is related to https://github.com/ace-diff/ace-diff/issues/49. However, I tested the fix in this PR and it's not really working. I wanted to close out the PR but it seems I don't have permission for it. So this is not a correct fix.

I am using angularjs wit typescript. I posted the setup in detail at https://stackoverflow.com/questions/51290734/cannot-read-property-acequire-of-undefined. Let me know if you have any suggestions. Willing to test it out :)

**Comment by ajinkyasuryawanshi-okta** [comment]
If you want, we can close this PR and continue discussion on https://github.com/ace-diff/ace-diff/issues/49 so other people might benefit. Thank you.

**Comment by ajinkyasurya** [comment]
Hi @JackuB thanks for getting back to me. Yes it is related to #49. However, I tested the fix in this PR and it's not really working. I wanted to close out the PR but it seems I don't have permission for it. So this is not a correct fix.

I am using angularjs wit typescript. I posted the setup in detail at https://stackoverflow.com/questions/51290734/cannot-read-property-acequire-of-undefined. Let me know if you have any suggestions. Willing to test it out :)

**Comment by ajinkyasurya** [comment]
If you want, we can close this PR and continue discussion on #49 so other people might benefit. Thank you.

**Pull request closed without merging**
